name: github_dart_repository
description: View github dart repository
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  get_it: ^7.6.4
  provider: ^6.0.5
  copy_with_extension: ^5.0.4
  infinite_scroll_pagination: ^4.0.0
  flutter_secure_storage: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  copy_with_extension_gen: ^5.0.2
flutter:
  uses-material-design: true
